### ISSUE TITLE
Ixa pipes java server keeps running even when the python process is killed

### ISSUE THREAD

**Issue by igabirondo16** [ikergarcia1996/Python-IXA-Pipes#1]
I am using this project for my bachelor thesis. I found out that when you kill the python process, the java server keeps running in the background. Therefore, when you try to execute the python wrapper for a second time, at initialization time it tries to bind a port that is already being used, and a java exception is raised.

**Comment by ikergarcia1996** [comment]
Hi!
Sorry for taking so long to reply, this is a project that is currently at a standstill and I have not developed it further. I have fixed the problem. 
Run "pip install --upgrade ixapipes". 

Do not forget to close the tokenizer and the posttager at the end of the python process

```python
from ixapipes.tok import IxaPipesTokenizer
tokenizer = IxaPipesTokenizer(language="en",notok=False, output_format="oneline")
print(tokenizer("Member of Parliament holds a minute's silence"))
tokenizer.close() # <--- If you forget this line the server will continue running 

```
